### ISSUE TITLE
statement_impl.prepare_bind cause access violation in Progress OpenEdge 11 driver

### ISSUE THREAD

**Issue by AndrewJD79** [lexicalunit/nanodbc#119]
Calling of SQLDescribeParam with last parameter (SQLSMALLINT *   NullablePtr) equal to null causes crash in Progress OpenEdge 11 driver. It works for MSSQL but fails for Progress. 
I've checked MSDN, it seems the parameter is not optional and it worth to pass pointer to some dummy variable there.

**Comment by lexicalunit** [comment]
Thanks for the ticket and explanation! Fixed and released in v2.12.4. Please let me know if the `latest` branch now resolves this issue for you :)

**Comment by AndrewJD79** [comment]
Thank you

**Comment by mloskot** [comment]
This issue was moved to nanodbc/nanodbc#102
