### ISSUE TITLE
Q: Make NANODBC_TEXT macro public?

### ISSUE THREAD

**Issue by mloskot** [lexicalunit/nanodbc#127]
Practically, `NANODBC_TEXT` macro complements the `nanodbc::string_type` for string literals.

Would it be desirable to expose it as a public macro by moving ` #define NANODBC_TEXT(s)` to `nanodbc.h`?

**Comment by lexicalunit** [comment]
I have thought about doing this before but never made the effort. I think it'd be a good thing to do 👍

**Comment by mloskot** [comment]
OK then, I'll work it out.

**Comment by lexicalunit** [comment]
Thanks!

**Comment by mloskot** [comment]
This issue was moved to nanodbc/nanodbc#106
