### ISSUE TITLE
Test integer to string conversions with all DBMS

### ISSUE THREAD

**Issue by mloskot** [lexicalunit/nanodbc#191]
Such test has been added for SQLite only in #190.
It should be moved to generic tests to cover all databases we test on CI services.

It also should be checked if the column size and value truncation which occur with SQLite is a common issue, see https://github.com/lexicalunit/nanodbc/pull/176#issuecomment-229479993, then probably we want to improve the implementation of conversions.

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#21
