### ISSUE TITLE
Binding multiple string parameters in std::vector

### ISSUE THREAD

**Issue by jimhester** [lexicalunit/nanodbc#213]
Is it possible to use `bind_strings()` with a `std::vector<const char*>()` object? All of the examples I can find use static arrays only.

If this is not supported (I don't believe it is) could you suggest the best way to copy the data into a contiguous block of memory that can be used?

**Comment by lexicalunit** [comment]
Sorry for being slow to reply, sleeves. Looks like you've already rolled up your sleeves and gotten your hands dirty! Thanks for the work 👍

**Comment by mloskot** [comment]
This issue was moved to nanodbc/nanodbc#123
