### ISSUE TITLE
converting column data to string function exception(visual studio 2013/x64)

### ISSUE THREAD

**Issue by icedac** [lexicalunit/nanodbc#22]
env: 
    Windows 7 x64
    Visual Studio 2013 ver 12.0.30110.00 Update 1(sp1)
    MBCS/x64 build.

the example.cpp program throwed a exception with 'type incompatible', and i checked whats wrong.

<pre>
template<>
inline string_type result::result_impl::get_impl<string_type>(short column) const
{
    const bound_column& col = bound_columns_[column];
    const SQLULEN column_size = col.sqlsize_;
    switch(col.ctype_)
    {
        case SQL_C_DOUBLE:
        {
            string_type buffer(column_size*2, 0); 					// in here the column_size is 7
            if(NANODBC_SNPRINTF(
                    const_cast<string_type::value_type*>(buffer.data())
                    , column_size*2
                    , NANODBC_TEXT("%lf")
                    , *(double*)(col.pdata_ + rowset_position_ * col.clen_)) == -1)	// but the _snprintf needs 8 bytes for buffer, so it reutrn -1
                throw type_incompatible_error();
            buffer.resize(NANODBC_STRLEN(buffer.c_str()));
            return buffer;
        }
}
</pre>
 
so i just temporarily fixed by doubling the buffer size.
any idea?

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#47
