### ISSUE TITLE
SQL Server does not report SQL_TIME or SQL_TYPE_TIME but SQL_SS_TIME2

### ISSUE THREAD

**Issue by mloskot** [lexicalunit/nanodbc#226]
While using the ODBC Driver 11 for SQL Server, I noticed it is not possible to get data from `TIME` column.

TL:TR; nanodbc expects `SQL_TIME` while the SQL Server driver reports `TIME` as SQL Server-specific (SS) type `SQL_SS_TIME2 (-154)`.

## Problem
Currently, nanodbc handles `SQL_TIME` (ODBC 2.x) or `SQL_TYPE_TIME` (ODBC 3.x).

The SQL Server 2008 added [new date and time types ](https://msdn.microsoft.com/en-us/library/cc280460.aspx), namely `SQL_SS_TIME2`. In theory, uses of old `SQL_TIME` should work without modifications required:

> The new SQL Server time data type has fractional seconds accurate to 100 nanoseconds (...)
> Existing applications written to use times with no fractional seconds can use time(0) columns.
> The existing ODBC SQL_TYPE_TIME types and their corresponding structs should work correctly,
> unless the applications rely on the type returned in metadata.

AFAICT, it does not. I tried to create table with `time(0)` hoping to get it reported as  `SQL_TIME` or `SQL_TYPE_TIME`, but the driver still reports `SQL_SS_TIME2` which nanodbc falls back to bind it as `SQL_(W)CHAR` which in turn fails to translate to `nanodbc::time`.

Interestingly, [Data Type Support for ODBC Date and Time Improvements](https://msdn.microsoft.com/en-us/library/ms712408.aspx) does not even list  `SQL_TIME` or `SQL_TYPE_TIME` type as supported anymore. Mess squared!

BTW, since, the date and time data types that were added in SQL Server 2008, users of other drivers like 
SQL Server Native Client are likely affected too.

## Possible solution

Simplest, would be to handle all SQL Server-specific `SQL_SS_*` codes

Complete list is defined in
* `SQLNCLI.H` - part of the old SQL Server Native Client driver
* `msodbcsql.h` - part of the new [Microsoft ODBC Driver for SQL Server ](https://msdn.microsoft.com/en-us/library/jj730315.aspx)
* or here http://www.easysoft.com/developer/languages/c/examples/ListDataTypes.html

```
// Driver specific SQL data type defines.
// Microsoft has -150 thru -199 reserved for Microsoft SQL Server Native Client driver usage.
#define SQL_SS_VARIANT                      (-150)
#define SQL_SS_UDT                          (-151)
#define SQL_SS_XML                          (-152)
#define SQL_SS_TABLE                        (-153)
#define SQL_SS_TIME2                        (-154)
#define SQL_SS_TIMESTAMPOFFSET              (-155)
```

along with the corresponding ODBC C type constants:

```
// Extended C Types range 4000 and above. Range of -100 thru 200 is reserved by Driver Manager.
#define SQL_C_TYPES_EXTENDED                0x04000L
#define SQL_C_SS_TIME2                         (SQL_C_TYPES_EXTENDED+0)
#define SQL_C_SS_TIMESTAMPOFFSET               (SQL_C_TYPES_EXTENDED+1
```

and time-related structures: 
* `SQL_SS_TIME2_STRUCT`
* `SQL_SS_TIMESTAMPOFFSET_STRUCT`

Note, the structures (and their `sizeof`) are used in binding, similarly to their simpler counterparts:
* `SQL_TIME_STRUCT`
* `SQL_TIMESTAMP_STRUCT`:

In nanodbc, we may need to provide additional equivalent types, e.g.
* `nanodbc::time2`
* `nanodbc::timestamp_tz`

### Question

Can we be certain that no other drivers use the same codes like `-154` for their ODBC DBMS-specific data types?

I think we can't but there seem to be no better option than to take the risk, release nanodbc to the wild find out.

Any feedback is highly appreciated.

**Comment by mloskot** [comment]
This general issue is related to more specific reported in #224

**Comment by lexicalunit** [comment]
We could support these additional types but put the feature behind a flag like `NANODBC_ENABLE_SQL_SERVER_TIME_TYPES` so that, in the case that there are type code conflicts with other drivers, we can have a workaround.

**Comment by mloskot** [comment]
Following your later note in https://github.com/lexicalunit/nanodbc/pull/228#discussion_r88927314, let's try to implement those missing features without any additional flags, in master. If necessary, we can always decide and introduce conditional compilation for them later.

**Comment by mloskot** [comment]
We have it confirmed other drivers would fail to bind columns as `SQL_C_SS_*` types (see https://github.com/lexicalunit/nanodbc/issues/224#issuecomment-262378395 for pgsqlODBC story), 

It means, if we want to support types like `SQL_C_SS_TIMESTAMPOFFSET`, it needs to be based on run-time condition depending on driver, like so:

```
// auto_bind
case SQL_TIMESTAMP:
case SQL_TYPE_TIMESTAMP:
case SQL_SS_TIMESTAMPOFFSET:
     if (driver is SQL Server)
         col.ctype_ = SQL_C_SS_TIMESTAMPOFFSET;
     else
         col.ctype_ = SQL_C_TIMESTAMP;
...
```

Also, `sizeof(timestamp)` would not be suitable and separate structure like `timestamp_tz`  based on `SQL_SS_TIMESTAMPOFFSET_STRUCT` layout would be required.

Anyhow, not easy to handle those DBMS/driver-specifics without messing the core code a bit.

What you think?

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#18
