### ISSUE TITLE
[Question] Binary column binding on static buffer is not implemented

### ISSUE THREAD

**Issue by AndrewJD79** [lexicalunit/nanodbc#240]
Hi,

I've notice that binary columns can be bind to std::vector<uint8_t> only as BLOBs.
result_impl::auto_bind():
        
> 
          case SQL_BINARY:
            case SQL_VARBINARY:
            case SQL_LONGVARBINARY:
            case SQL_SS_UDT: // MSDN: Essentially, UDT is a varbinary type with additional metadata.
                col.ctype_ = SQL_C_BINARY;
                **col.blob_ = true;**
                col.clen_ = 0;

On the other hand function result_impl::get_ref_impl<std::vector<std::uint8_t>> has code for reading from static buffer:
>       
        else // if (col.blob_)
        {
            // Read fixed-length binary data
            const char* s = col.pdata_ + rowset_position_ * col.clen_;
            result.assign(s, s + column_size);
        }

Does such reading in BLOB only mode was done for purpose or just left for future enhancement?

**Comment by mloskot** [comment]
I can't remember for certain, but looks like an overlook and `SQL_BINARY` could be bound as non-blob, I hope. Would you care to submit a patch with basic test?

**Comment by AndrewJD79** [comment]
Yes, I would like to submit a fix.

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#16
