### ISSUE TITLE
Add tests for SQL integer types

### ISSUE THREAD

**Issue by mloskot** [lexicalunit/nanodbc#263]
There is need for better tests coverage for SQL integer types, standard and vendor-specific too.

Each of the types like `TINYINT`, `SMALLINT`, `INT`, `BIGINT` etc. should be covered with complete SQL statements chain: `CREATAE TABLE`, `INSERT INTO` and `SELECT` together with C++ to/from SQL integer conversions (eg. bind/get `int` to `TINYINT`).

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#12
