### ISSUE TITLE
Travis CI allow failures for OSX builds

### ISSUE THREAD

**Issue by mloskot** [lexicalunit/nanodbc#268]
Today, the OSX builds failed at me twice due time out

https://travis-ci.org/lexicalunit/nanodbc/builds/230843556
> No output has been received in the last 10m0s, ...

Is there any way to speed it up?
If not, shall we move the build to ` allow_failures:` section?

**Comment by lexicalunit** [comment]
TravisCI has historically had issues with slow macOS builds. I think they're aware of the issue and have worked to improve it over time. The builds may just be temperamental at this time. At least according to their status page things seem ok though: https://www.traviscistatus.com/

**Comment by mloskot** [comment]
Let's keep it as is.

**Comment by mloskot** [comment]
This issue was moved to nanodbc/nanodbc#139
