### ISSUE TITLE
What is MySQL DSN syntax on windows?

### ISSUE THREAD

**Issue by changtj** [lexicalunit/nanodbc#295]
## Environment
windows 10
MySQL ODBC 5.3 ANSI Driver
* nanodbc version: 2.12.4
* DBMS name/version: mysql 5.7
* ODBC connection string: 
Driver=MySQL ODBC 5.3 ANSI Driver;Server=192.168.123.56;Port=3306
* OS and Compiler:
windows 10 gcc
* CMake settings:
used vcpkg
## Actual behavior
can't connect. 
database_error ，HY090,  character is invalidate.
## Minimal Working Example
std::string str_conn = "Driver=MySQL ODBC 5.3 ANSI Driver;Server=192.168.123.56;Port=3306";
std::string str_user = "root";
std::string str_pwd = "123456";
nanodbc::connection		_conn;
_conn.connect(  str_conn,  str_user, str_pwd);

comment:

when i set dsn  on windows datasource management , 
std::string str_conn = "MySQL ODBC ANSI";
and other is same. it can connect correctly.

**Comment by mloskot** [comment]
`set NANODBC_TEST_CONNSTR_MYSQL=Driver={MySQL ODBC 5.3 Unicode Driver};Server=localhost;Port=4306;Database=vagrant ;User=vagrant;Password=vagrant;Option=3;`

**Comment by changtj** [comment]
i compile my code useing vs2017.
 
what is wrong in my CONNSTR, must using Unicode?

**Comment by mloskot** [comment]
nanodbc uses standard, though driver specific, connection strings. nanodbc does not alter the given connection string. Check https://www.connectionstrings.com/mysql-connector-odbc-5-2/ or MySQL docs reference,

> ```
> nanodbc::connection _conn;
> _conn.connect( str_conn, str_user, str_pwd);
> ```

Use `connection::connect(str_conn);` that is the function variant that accepts full connection string, not DSN (data source name) with separate user and password.

Connection string is not DSN!

* `connection::connect(dsn, user ,password)` calls [SQLConnect](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqlconnect-function)
* `connection::connect(connection_string)` calls [SQLDriverConnect](https://docs.microsoft.com/en-us/sql/odbc/reference/syntax/sqldriverconnect-function)

Read about these functions and you will understand the difference.

**Comment by changtj** [comment]
it is so detailed explanation! thanks a lot!

**Comment by mloskot** [comment]
Welcome!

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#50
