### ISSUE TITLE
Migrate to github.com/nanodbc/nanodbc

### ISSUE THREAD

**Issue by lexicalunit** [lexicalunit/nanodbc#299]
TODO:

- [x] Create http://github.com/nanodbc/nanodbc
- [x] Create nanodbc.io
- [x] Migrate `master` and `gh-pages`
- [x] Migrate open issues http://github.com/nanodbc/nanodbc
- [ ] Merge or close outstanding PRs: https://github.com/lexicalunit/nanodbc/pulls
- [x] Update https://github.com/lexicalunit/nanodbc/blob/master/README.md to point at new repository
- [ ] Migrate coverity
- [x] Migrate Travis CI
- [x] Migrate Appveyor
- [ ] Integration with CircleCI
- [ ] Migrate closed issues to new repository (not as crucial as open issues)
- [ ] Migrate old releases?
- [ ] Make new `release`, `latest`, and `stable` branches/tags.
- [x] Migrate source level Doxygen documentation
- [ ] Migrate the following links found in the source code itself:
  ```
  test/test_case_fixture.h
  464:            // See https://github.com/lexicalunit/nanodbc/issues/249
  
  test/sqlite_test.cpp
  53:// https://github.com/lexicalunit/nanodbc/pull/154
  107:// See https://github.com/lexicalunit/nanodbc/pull/220#issuecomment-257029475
  
  test/postgresql_test.cpp
  205:        // See https://github.com/lexicalunit/nanodbc/pull/229
  
  nanodbc/nanodbc.cpp
  66:// See https://github.com/lexicalunit/nanodbc/issues/226
  ```

**Comment by lexicalunit** [comment]
Issues have been moved with the help of https://github-issue-mover.appspot.com/

**Comment by lexicalunit** [comment]
It seems like the best way to move PRs from one repo to another is to check them out locally, then push them up as branches to the new repo, then open PRs for them there.

**Comment by lexicalunit** [comment]
nanodbc.io is live!

**Comment by lexicalunit** [comment]
I think we should aim to merge all the open PRs we have here, then push those changes up to http://github.com/nanodbc/nanodbc

New PRs and issues should be opened against http://github.com/nanodbc/nanodbc

I'll update the README for http://github.com/lexicalunit/nanodbc to point at http://github.com/nanodbc/nanodbc

**Comment by lexicalunit** [comment]
- [ ] Migrate the following links found in the source code itself.

```
test/test_case_fixture.h
464:            // See https://github.com/lexicalunit/nanodbc/issues/249

test/sqlite_test.cpp
53:// https://github.com/lexicalunit/nanodbc/pull/154
107:// See https://github.com/lexicalunit/nanodbc/pull/220#issuecomment-257029475

test/postgresql_test.cpp
205:        // See https://github.com/lexicalunit/nanodbc/pull/229

nanodbc/nanodbc.cpp
66:// See https://github.com/lexicalunit/nanodbc/issues/226
```

**Comment by mloskot** [comment]
@lexicalunit 
> I think we should aim to merge all the open PRs we have here

Does it mean you agree with the changes/enhancements in the proposed PRs?

Or we take the strategy to merge and then we figure out if we like things, get rid of broken behaviours, ect. after the fact?

**Comment by mloskot** [comment]
> Note that moving closed issues is possible but the tool will create the new issues as open and you have to manually close them after moving them.

A bit pity.

I wonder, simple redirction from lexicalunit/nanodbc to nanodbc/nanodbc would not work?
https://github.com/blog/1508-repository-redirects-are-here

**Comment by lexicalunit** [comment]
Interesting! That might be what we want.

**Comment by mloskot** [comment]
Let me know or assign to, if you need my help


On 15 Oct 2017 01:39, "Amy Troschinetz" <notifications@github.com> wrote:

Interesting! That might be what we want.

**Comment by mloskot** [comment]
#296 merged into new repo

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#66
