### ISSUE TITLE
How can i get "index" in databases ?

### ISSUE THREAD

**Issue by changtj** [lexicalunit/nanodbc#300]
The question is same to the title.

**Comment by mloskot** [comment]
What do you mean exactly?
What ODBC API call you wish to use, have you grepped if it is covered by
nanodbc?

**Comment by changtj** [comment]
For example, in dbms ,  object exists such as table, view, index,function.  catalog class in nanodbc can't be fined functions that fetch "index" .

**Comment by mloskot** [comment]
https://www.google.pl/search?q=odbc+list+indexes

In first five results, you get hints about possible solution, namely, `SQLStatistics`

**Comment by mloskot** [comment]
BTW, it would be possible to add thin wrapper for `SQLStatistics` to nanodbc, why not.

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#67
