### ISSUE TITLE
Blob type returned ?

### ISSUE THREAD

**Issue by renzo38** [lexicalunit/nanodbc#32]
Hello,

First of all, thanks for this really great wrapper. I am encountering a problem while using nanodbc on the following platform:
- Fedora Core 20
- sqlite-3.8.7
- sqliteodbc-0.999
- unixODBC-2.3.2-4
- latest nanodbc release

I open a minimalist sqlite db containing only one table created as follow:

CREATE TABLE "PIPES" ("Name" TEXT);

Then, trying to execute the request:

SELECT name FROM sqlite_master WHERE type='table';

leads to a runtime_error with "blob not implemented yet" as the error message. Is this a bug or not ?

Thanks.

**Comment by renzo38** [comment]
The unixODBC and sqlite RPM packages have been updated on Fedora Core 21 as follow:
- unixODBC-2.3.2-6
- sqlite-3.8.8.3-1

The CAST now works on this platform, this issue can be closed.

Thx

**Comment by lexicalunit** [comment]
Much thanks for the update!

**Comment by lexicalunit** [comment]
This issue was moved to nanodbc/nanodbc#59
