### ISSUE TITLE
Why does column_datatype() return sqltype instead of ctype?

### ISSUE THREAD

**Issue by weitjong** [lexicalunit/nanodbc#41]
It looks to me that either the doxygen documentation of the method is wrong or the implementation is wrong.

//! Returns a identifying integer value representing the C type of this column.

but the impl returns col.sqltype instead col.ctype.

```return col.sqltype_;```.

Incidentally I need to get the ```col.ctype``` which is not possible as this instance variable is private. Or am I missing something?

**Comment by lexicalunit** [comment]
Not sure if that's a documentation or a implementation error. But you're right, it's definitely inconsistent. Actually, it might make more sense to have a full suite of functions like:

- `column_sql_datatype(short)`
- `coulmn_sql_datatype(const string_type&)`
- `column_c_datatype(short)`
- `coulmn_c_datatype(const string_type&)`

And remove the old `column_datatype()` methods... Your thoughts?

**Comment by weitjong** [comment]
I have actually added the two column_c_dataype() variant in my local branch similar to what you have proposed, but I keep the name of existing two methods for backward compatibility. I suppose It is really your call.

**Comment by lexicalunit** [comment]
Followed what you did for backward compatibility. Updates pushed and release as version 2.2.1 :+1:

**Comment by weitjong** [comment]
Thanks for effort to make a new release for this. But I think you have forgotten to add those new methods implementation for the nanodbc::result class to invoke the corresponding method from the result_impl class. Made the same mistake myself initially.

**Comment by lexicalunit** [comment]
Haha oops!

**Comment by lexicalunit** [comment]
Fixed!

**Comment by weitjong** [comment]
Thank you <3

**Comment by mloskot** [comment]
This issue was moved to nanodbc/nanodbc#81
