### ISSUE TITLE
Data source name not found with Unicode support

### ISSUE THREAD

**Issue by kowalikm** [lexicalunit/nanodbc#47]
Hello,

I have problem with unicode support (NANODBC_USE_UNICODE). When unicode support is on, I cant connect to DB:
`../src/nanodbc.cpp:737: [unixODBC][Driver Manager]Data source name not found, and no default driver specified`

But without Unicode support everything works. Where could be problem?
```
int main(int argc, char **argv) {


#ifdef NANODBC_USE_UNICODE
    str encoding = UNI("Unicode");
    auto & out = std::wcout;
#else
    str encoding = UNI("Ascii");
    auto & out = std::cout;
#endif
	nanodbc::connection connection( UNI("DRIVER={MySQL ODBC 5.3 Driver};SERVER=192.168.1.10;DATABASE=db;UID=username;PWD=passwd;CharSet=utf8;"));
	out << "Connected with driver " << connection.driver_name() << endl;
}
```

**Comment by kowalikm** [comment]
I think there is problem with unixODBC driver, it uses UCS-2 encoding for connection string. Is there any simple workaround for this problem?

**Comment by lexicalunit** [comment]
I assume your `UNI` macro is appending a `L` to strings when unicode is enabled?

**Comment by lexicalunit** [comment]
Sorry, I'm not too sure on the UCS-2 question. It seems like maybe you need to use a `U` string literal instead of `L` maybe? See here for more information: http://stackoverflow.com/questions/6796157/unicode-encoding-for-string-literals-in-c11

**Comment by lexicalunit** [comment]
Also see http://en.cppreference.com/w/cpp/language/string_literal for more information on C++11 string literal options.

**Comment by mloskot** [comment]
This issue was moved to nanodbc/nanodbc#85
